# 6- Adding and Removing Columns and Rows

Much like other essential processes for data analysis and data cleaning, pandas offers multiple ways of adding and removing columns and rows.

In [1]:
# Importing pandas
import pandas as pd

In [2]:
# Creating and showing beatles DF
beatles = pd.DataFrame(
    {
        'first': ['John', 'Paul', 'George', 'Ringo'],
        'last': ['Lennon', 'McCartney', 'Harrison', 'Starr'],
        'birth_year': [1940, 1942, 1943, 1940],
        'email': [
            'john.lennon@email.com',
            'paul.mccartney@email.com',
            'george.harrison@email.com',
            'ringo.starr@email.com',
        ],
        'band': 'Beatles',
    }
)

beatles

    first       last  birth_year                      email     band
0    John     Lennon        1940      john.lennon@email.com  Beatles
1    Paul  McCartney        1942   paul.mccartney@email.com  Beatles
2  George   Harrison        1943  george.harrison@email.com  Beatles
3   Ringo      Starr        1940      ringo.starr@email.com  Beatles

In [3]:
# Creating and showing rolling stones Df
rolling_stones = pd.DataFrame(
    {
        'first': ['Mick', 'Keith', 'Brian', 'Bill', 'Charlie'],
        'last': ['Jagger', 'Richards', 'Jones', 'Wyman', 'Watts'],
        'birth_year': [1943, 1943, 1942, 1936, 1941],
        'email': [
            'mick.jagger@email.com',
            'keith.richards@email.com',
            'brian.jones@email.com',
            'bill.wyman@email.com',
            'charlie.watts@email.com',
        ],
        'band': 'Rolling Stones',
    }
)
rolling_stones

     first      last  birth_year                     email            band
0     Mick    Jagger        1943     mick.jagger@email.com  Rolling Stones
1    Keith  Richards        1943  keith.richards@email.com  Rolling Stones
2    Brian     Jones        1942     brian.jones@email.com  Rolling Stones
3     Bill     Wyman        1936      bill.wyman@email.com  Rolling Stones
4  Charlie     Watts        1941   charlie.watts@email.com  Rolling Stones

## Creating and Removing columns

One of the simplest ways of creating rows is to just assign a new column name to a set of values the size of the DF. This is as simple as it sounds, instead of accessing an existing column when modifying them, access a column with the desired column name and assign it a Series object.

This can be done for multiple rows at a time as well, just use the list operator for selecting multiple rows and assign it values corresponding to the number of newly created rows.

In [4]:
# Concatenating two rows, separated by a space
beatles['first'] + ' ' + beatles['last']

0        John Lennon
1     Paul McCartney
2    George Harrison
3        Ringo Starr
dtype: object

In [5]:
# Generating series by concatenating two columns and assigning it to existing column
beatles['full_name'] = beatles['first'].str.cat(beatles['last'], sep=' ')
beatles['full_name']

0        John Lennon
1     Paul McCartney
2    George Harrison
3        Ringo Starr
Name: full_name, dtype: object

Removing columns is likewise a very simple process, just use pandas's `.drop` method and specify the names of the columns to be dropped.

In [6]:
# Removing first and last columns
beatles.drop(columns=['first', 'last'], inplace=True)
beatles

   birth_year                      email     band        full_name
0        1940      john.lennon@email.com  Beatles      John Lennon
1        1942   paul.mccartney@email.com  Beatles   Paul McCartney
2        1943  george.harrison@email.com  Beatles  George Harrison
3        1940      ringo.starr@email.com  Beatles      Ringo Starr

You can also use pandas built-in methods for operating in columns to manipulate them. In this case, since we created a new column `full_name` by concatenating two existing rows, we can do the reverse process in order to separate the column into two.

This is easily done by using the `expand` parameter that already creates columns from the output of the method. Not all methods offer this, but be aware that some methods do.

In [7]:
# Splitting full name into two (without expand being true)
beatles['full_name'].str.split(' ')

0        [John, Lennon]
1     [Paul, McCartney]
2    [George, Harrison]
3        [Ringo, Starr]
Name: full_name, dtype: object

In [8]:
# Splitting full name into two (with expand option being true)
beatles['full_name'].str.split(' ', expand=True)

        0          1
0    John     Lennon
1    Paul  McCartney
2  George   Harrison
3   Ringo      Starr

In [9]:
# Re-creating first and last columns
beatles[['first', 'last']] = beatles['full_name'].str.split(' ', expand=True)
beatles

,birth_year,email,band,full_name,first,last
0,1940,john.lennon@email.com,Beatles,John Lennon,John,Lennon
1,1942,paul.mccartney@email.com,Beatles,Paul McCartney,Paul,McCartney
2,1943,george.harrison@email.com,Beatles,George Harrison,George,Harrison
3,1940,ringo.starr@email.com,Beatles,Ringo Starr,Ringo,Starr

In [10]:
beatles.drop(columns='full_name', inplace=True)

## Creating and Removing rows

As simple as it is to create columns in pandas, the same doesn't apply to creating rows. The way you find the easiest in the internet is by using the `.append` method, this doesn't work in pandas as of version `2.0`. There are alternatives though.

The first way is to use a `location` function to add rows at the end of the DF. You can find the index of the location to be added by using `len(df)`. This however isn't the best way if you may want to add many rows, since you would constantly need to reanalyse the size of the DF.

To counter this problem pandas offers a function `concat`. This isn't a `DataFrame` method, instead an actual function from the pandas library. Using it is still pretty simple, but it comes with some caveats. Pass it a list of DF/Series to concatenate as the first argument, the other arguments are optional, the first recommended one is `ignore_index` (that removes the existing indexes from either DF and creates a new set of them), the second is join (that allows you to specify how you wish the tables to be joined, inner, outer, ...).

You should use `.concat` to join two DF together as well.

In [11]:
beatles.loc[len(beatles)] = {
    'first': 'Brian',
    'last': 'Epstein',
    'birth_year': 1934,
    'email': 'brian.epstein@email.com',
    'band': 'Beatles',
}

beatles

   birth_year                      email     band   first       last
0        1940      john.lennon@email.com  Beatles    John     Lennon
1        1942   paul.mccartney@email.com  Beatles    Paul  McCartney
2        1943  george.harrison@email.com  Beatles  George   Harrison
3        1940      ringo.starr@email.com  Beatles   Ringo      Starr
4        1934    brian.epstein@email.com  Beatles   Brian    Epstein

To remove a row, just use the same `.drop` function as you would for removing columns, its a good idea to use conditional filters for removing columns, or just specify the index to be removed.

In [12]:
beatles.drop(index=beatles[beatles['last'] == 'Martin'].index, inplace=True)

In [13]:
# Adding new member to beatles DF via concat
beatles = pd.concat(
    [
        beatles,
        pd.DataFrame(
            {
                'first': ['George'],
                'last': ['Martin'],
                'birth_year': [1926],
                'email': ['george.martin@email.com'],
                'band': 'Beatles',
            }
        ),
    ],
    ignore_index=True,
)
beatles

   birth_year                      email     band   first       last
0        1940      john.lennon@email.com  Beatles    John     Lennon
1        1942   paul.mccartney@email.com  Beatles    Paul  McCartney
2        1943  george.harrison@email.com  Beatles  George   Harrison
3        1940      ringo.starr@email.com  Beatles   Ringo      Starr
4        1934    brian.epstein@email.com  Beatles   Brian    Epstein
5        1926    george.martin@email.com  Beatles  George     Martin

In [14]:
# Creating rivals DF by joining beatles and rolling stones DFs
rivals = pd.concat([beatles, rolling_stones], ignore_index=True)
rivals

    birth_year                      email            band    first       last
0         1940      john.lennon@email.com         Beatles     John     Lennon
1         1942   paul.mccartney@email.com         Beatles     Paul  McCartney
2         1943  george.harrison@email.com         Beatles   George   Harrison
3         1940      ringo.starr@email.com         Beatles    Ringo      Starr
4         1934    brian.epstein@email.com         Beatles    Brian    Epstein
5         1926    george.martin@email.com         Beatles   George     Martin
6         1943      mick.jagger@email.com  Rolling Stones     Mick     Jagger
7         1943   keith.richards@email.com  Rolling Stones    Keith   Richards
8         1942      brian.jones@email.com  Rolling Stones    Brian      Jones
9         1936       bill.wyman@email.com  Rolling Stones     Bill      Wyman
10        1941    charlie.watts@email.com  Rolling Stones  Charlie      Watts

In [15]:
# Removing George Martin row from Rivals DF
rivals.drop(index=4, inplace=True)
rivals

    birth_year                      email            band    first       last
0         1940      john.lennon@email.com         Beatles     John     Lennon
1         1942   paul.mccartney@email.com         Beatles     Paul  McCartney
2         1943  george.harrison@email.com         Beatles   George   Harrison
3         1940      ringo.starr@email.com         Beatles    Ringo      Starr
5         1926    george.martin@email.com         Beatles   George     Martin
6         1943      mick.jagger@email.com  Rolling Stones     Mick     Jagger
7         1943   keith.richards@email.com  Rolling Stones    Keith   Richards
8         1942      brian.jones@email.com  Rolling Stones    Brian      Jones
9         1936       bill.wyman@email.com  Rolling Stones     Bill      Wyman
10        1941    charlie.watts@email.com  Rolling Stones  Charlie      Watts

In [18]:
# Creating filter for people born after 1942
filt = rivals['birth_year'] > 1942

# Removing rows based on filter
rivals.drop(index=rivals[filt].index, inplace=True)

# Resetting indexes and showing DF
rivals.reset_index(drop=True, inplace=True)
rivals

   birth_year                     email            band    first       last
0        1940     john.lennon@email.com         Beatles     John     Lennon
1        1942  paul.mccartney@email.com         Beatles     Paul  McCartney
2        1940     ringo.starr@email.com         Beatles    Ringo      Starr
3        1926   george.martin@email.com         Beatles   George     Martin
4        1942     brian.jones@email.com  Rolling Stones    Brian      Jones
5        1936      bill.wyman@email.com  Rolling Stones     Bill      Wyman
6        1941   charlie.watts@email.com  Rolling Stones  Charlie      Watts