# 7- Sorting data

Sorting data is a quintessential tool in data analysis, it makes it easier to see patterns in data, or to simply organize the data available. Pandas much like other data analysis tools, offer support for sorting data.

It revolves on using two different methods, either the `.sort_values` or the `.sort_index` methods.

## `.sort_values`

The `.sort_values` method takes the value to sort the DF based on in the parameter `by`, and `ascending` (the order in which to sort the data ascending or descending, true or false). Both parameters can receive lists, the latter requires the first to receive the list, meaning you can only set the value of the second to a list if you have set the first to a list.

The reason why you would set the value of `by` to a list is to order the DF by a multitude of values. It works by ordering by each argument of the list in the order they're presented in said list. This allows `ascending` to be set to a list that orders the corresponding index argument of the `by` argument list should be ordered by.

## `.sort_index`

This is an easy way of correcting the order of the indexes of the DF.

In [ ]:
# Importing pandas
import pandas as pd

In [2]:
# Creating beatles DF
beatles = pd.DataFrame(
    {
        'first': ['John', 'Paul', 'George', 'Ringo'],
        'last': ['Lennon', 'McCartney', 'Harrison', 'Starr'],
        'birth_year': [1940, 1942, 1943, 1940],
        'email': [
            'john.lennon@email.com',
            'paul.mccartney@email.com',
            'george.harrison@email.com',
            'ringo.starr@email.com',
        ],
    }
)

In [ ]:
# Sorting DF by last name in descending order
beatles.sort_values(by='last', ascending=False)

    first       last  birth_year                      email
3   Ringo      Starr        1940      ringo.starr@email.com
1    Paul  McCartney        1942   paul.mccartney@email.com
0    John     Lennon        1940      john.lennon@email.com
2  George   Harrison        1943  george.harrison@email.com

In [ ]:
# Sorting DF by last name, then by first name in descending order
beatles.sort_values(by=['last', 'first'], ascending=False)

    first       last  birth_year                      email
3   Ringo      Starr        1940      ringo.starr@email.com
1    Paul  McCartney        1942   paul.mccartney@email.com
0    John     Lennon        1940      john.lennon@email.com
2  George   Harrison        1943  george.harrison@email.com

In [ ]:
# Sorting DF by last name, then by first name in descending order and the second in ascending order
beatles.sort_values(by=['last', 'first'], ascending=[False, True], inplace=True)
beatles

    first       last  birth_year                      email
3   Ringo      Starr        1940      ringo.starr@email.com
1    Paul  McCartney        1942   paul.mccartney@email.com
0    John     Lennon        1940      john.lennon@email.com
2  George   Harrison        1943  george.harrison@email.com

In [ ]:
# Resetting DF's indexes
beatles.sort_index(inplace=True)
beatles

    first       last  birth_year                      email
0    John     Lennon        1940      john.lennon@email.com
1    Paul  McCartney        1942   paul.mccartney@email.com
2  George   Harrison        1943  george.harrison@email.com
3   Ringo      Starr        1940      ringo.starr@email.com